---
- name: Demonstrate Rolling Update with Error Handling
  hosts: all
  become: yes


  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      register: apt_result

    - name: Install Apache2 web server
      apt:
        name: apache2
        state: present

    - name: Ensure Apache is started and enabled
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Deploy custom index page with hostname identification
      copy:
        content: "<h1>Ansible Lab</h1><p>Served by: {{ inventory_hostname }}</p>"
        dest: /var/www/html/index.html
